#!/bin/bash

export MY_KEYSTORE_FILE="/home/vlad805/git/androidkeystore.jks"
export MY_KEYSTORE_PASS="myNadusik"
export MY_KEY_NAME="alias"
export WS="/home/vlad805/git/spirit2_original"
export PROJ="src"

printf $'Starting...\n'

needInstall=0

while [ -n "$1" ]
do
	case "$1" in
		-i) needInstall=1 ;;
		*) break ;;
	esac
	shift;
done

printf $'Removing previous files...'
rm -rf obj
rm -rf libs
printf $' OK\n'

printf $'Creating libs directory'
mkdir libs
printf $' OK\n'

printf $'Android update project...\n'
android update project --target android-21 --path . --name $PROJ
printf $'Done.\n'

printf $'Building C code (ndk)...\n'
time /home/vlad805/Android/Sdk/ndk-bundle/build/ndk-build 2>/dev/null #2>&1 |grep -i error
printf $'Done.\n'

mv libs/armeabi/s2d libs/armeabi/libs2d.so

printf $'Start ant...\n'
ant -q clean release

jarsigner -storepass $MY_KEYSTORE_PASS -sigalg MD5withRSA -digestalg SHA1 -keystore $MY_KEYSTORE_FILE -signedjar bin/$PROJ-release-unaligned.apk bin/$PROJ-release-unsigned.apk $MY_KEY_NAME
printf $'Done\n'
printf $'Archiving...\n'
zipalign -f 4 bin/$PROJ-release-unaligned.apk bin/$PROJ-release.apk
printf $'OK\n'

if [ "$needInstall" = "1" ]
then
	printf $'Installing apk via adb...'
	adb install -r bin/$PROJ-release.apk
	printf $' OK\nLaunching...'
	adb shell am start -n fm.a2d.sf/fm.a2d.sf.gui_act
	printf $' OK'
fi
